image: debian:experimental

before_script:
  - export TERM=dumb
  - apt-get update -qq
  - apt-get install -y -qq pkg-config build-essential cmake doxygen graphviz postgresql-server-dev-9.6 libpq-dev libglm-dev libassimp-dev lua5.3 liblua5.3-dev libsdl2-dev libenet-dev libcurl4-openssl-dev opencl-c-headers
  - cmake --version

build:
  script:
    - make -j 4
    - make tests ARGS="--gtest_filter=-DatabaseModelTest.*:ConnectionPoolTest.*:WorldRendererTest.testCreate"

pages:
  script:
    - make doc
    - mv build-debug/html/ public/
  artifacts:
    paths:
    - public
  only:
    - master
