image: registry.gitlab.com/mgerhardy/engine-docker:master

stages:
  - build
  - test
  - analyse

variables:
  CCACHE_BASEDIR: ${CI_PROJECT_DIR}
  CCACHE_DIR: ${CI_PROJECT_DIR}/ccache
  BUILD_DIR: ${CI_PROJECT_DIR}/build

.buildcache: &buildcache
  cache:
    key: ${CI_JOB_NAME}-cache
    paths:
      - ccache/
      - build/

build-unity:
  <<: *buildcache
  stage: build
  script:
    - cmake -H. -B${BUILD_DIR} -DDISABLE_UNITY=Off
    - make -j 4 all -C ${BUILD_DIR}

build-non-unity:
  <<: *buildcache
  stage: build
  script:
    - cmake -H. -B${BUILD_DIR} -DDISABLE_UNITY=On
    - make -j 4 all -C ${BUILD_DIR}

.test:
  variables:
    POSTGRES_DB: enginetest
    POSTGRES_USER: engine
    POSTGRES_PASSWORD: engine
    DB_HOST: postgres
    DB_USER: engine
    DB_PASSWORD: engine
    DB_NAME: enginetest
  services:
    - postgres:latest
  stage: test
  dependencies:
    - build
  script:
    - make -j 4 tests-run
  artifacts:
    reports:
      junit: build/*/gtest.xml
