image: registry.gitlab.com/mgerhardy/engine-docker:master

build:
  script:
    - make -j 4
    - make tests ARGS="--gtest_filter=-DatabaseModelTest.*:ConnectionPoolTest.*:WorldRendererTest.testCreate:UIShaderTest.*:FrontendShaderTest.*"

pages:
  script:
    - make doc
    - mv build/Debug/html/ public/
  artifacts:
    paths:
    - public
  only:
    - master
