image: registry.gitlab.com/mgerhardy/engine-docker:master

stages:
  - build
  - test
  - analyse

before_script:
  - mkdir -p ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/ccache

cache:
  paths:
    - ccache/

build:
  stage: build
  script:
    - make -j 4
  artifacts:
    paths:
    - build/Debug

test:
  stage: test
  dependencies:
    - build
  script:
    - cd build/Debug
    - ./tests

.analyse:cppcheck:
  stage: analyse
  script:
    - cppcheck --xml-version=2 -j 4 --enable=all --config-exclude=contrib/libs/ --project=build/Debug/compile_commands.json src 2> cppcheck.xml
  artifacts:
    paths:
    - cppcheck.xml

analyse:valgrind:
  stage: analyse
  dependencies:
    - build
  script:
    - cd build/Debug
    - valgrind --xml=yes --xml-file=valgrind.xml ./tests --gtest_filter=CoreTest.*:CameraTest.*:StringTest.*
  artifacts:
    paths:
    - build/Debug/valgrind.xml

pages:
  script:
    - make doc
    - mv build/Debug/html/ public/
  artifacts:
    paths:
    - public
  only:
    - master
