before_script:
  - apt-get update -qq && apt-get install -y -qq cmake libglm-dev libassimp-dev lua5.3 liblua5.3-dev libsdl2-dev postgresql-server-dev-9.5 libpq-dev
  - cmake --version
  - gcc --version

build:
  script:
    - make
