dist: trusty
sudo: false

os:
  - linux
  - osx

git:
  depth: 3

language: generic

addons:
  apt:
    packages:
    - zlib1g-dev
    - g++-7
    - gcc-7
    - clang-3.8
    - libdbus-1-dev
    - make
    - cmake
    - cmake-data
    - libasound2-dev
    - libpulse-dev
    - libaudio-dev
    - libx11-dev
    - libxext-dev
    - libxrandr-dev
    - libxcursor-dev
    - libxi-dev
    - libxinerama-dev
    - libxxf86vm-dev
    - libxss-dev
    - libgl1-mesa-dev
    - libesd0-dev
    - libdbus-1-dev
    - libgles1-mesa-dev
    - libgles2-mesa-dev
    - libegl1-mesa-dev
    - libibus-1.0-dev
    - postgresql-server-dev-all
    - libpq-dev
    - libenet-dev
    - libgtk-3-dev
    - qt5-default
    - qtbase5-dev
    - libmirclient-dev
    - ocl-icd-libopencl1
    - ocl-icd-opencl-dev
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake 3.x

# currently not available
#    - opencl-c-headers

script:
  - $CXX --version
  - make -j 4
  - make tests ARGS="--gtest_filter=-DatabaseModelTest.*:ConnectionPoolTest.*:WorldRendererTest.testCreate:UIShaderTest.*:FrontendShaderTest.*"

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7"; export CC="gcc-7"; fi
  - if [ "$CXX" = "clang++" ]; then export CXXFLAGS=-Qunused-arguments; export CFLAGS=-Qunused-arguments; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then gem install xcpretty; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then gem install xcpretty-travis-formatter; fi

#  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install postgresql; fi

cache:
  - apt
  - ccache
