language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
         - COMPILER="CC=gcc-7 && CXX=g++-7"
      before_install: eval "${COMPILER}"
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
    - os: osx
      osx_image: xcode10
      script:
        - mkdir build && cd build
        - cmake .. -DDISABLE_UNITY=On
        - cmake --build .
    - os: windows
      script:
        - mkdir build && cd build
        - cmake .. -DDISABLE_UNITY=On
        - cmake --build .
