version: 0.1-{build}

environment:
  INTELOCLSDKROOT: C:\Program Files (x86)\Intel\OpenCL SDK\5.3

image: Visual Studio 2017

configuration: Release

branches:
  only:
  - master

clone_depth: 10

# vcpkg enet, imgui are already available, but no on appveyor yet
# assimp, qt5 don't build
#  lua glm glslang gtest curl libuv zlib
before_build:
  - vcpkg install sdl2 libpq
  - ps: Start-FileDownload "http://registrationcenter-download.intel.com/akdlm/irc_nas/8386/intel_sdk_for_opencl_2015_r3_x64_setup.msi"
  - start /wait msiexec /i intel_sdk_for_opencl_2015_r3_x64_setup.msi /qn  /l*v msiexec.log
  - cmake -DTOOLS=OFF -G "Visual Studio 15 2017"

build:
  parallel: true
  project: tests-core.sln

artifacts:
  - name: Tests
    path: vengi-tests-core.exe

services:
  - postgresql          # start PostgreSQL 9.5 service

test_script:
  - cmd: vengi-tests-core.exe --gtest_output=xml:tests.xml

on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
