version: 0.1-{build}

environment:
  INTELOCLSDKROOT: C:\Program Files (x86)\Intel\OpenCL SDK\5.3

image: Visual Studio 2017

configuration: Release

branches:
  only:
  - master

clone_depth: 10

before_build:
  - ps: Start-FileDownload "http://registrationcenter-download.intel.com/akdlm/irc_nas/8386/intel_sdk_for_opencl_2015_r3_x64_setup.msi"
  - start /wait msiexec /i intel_sdk_for_opencl_2015_r3_x64_setup.msi /qn  /l*v msiexec.log
  - cmake -DTOOLS=OFF -G "Visual Studio 15 2017"

build:
  parallel: true
  project: tests.sln

artifacts:
  - name: Tests
    path: tests.exe

test_script:
  - cmd: tests.exe --gtest_output=xml:tests.xml

on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
