version: 0.1-{build}

environment:
  INTELOCLSDKROOT: C:\Program Files (x86)\Intel\OpenCL SDK\5.3

image: Visual Studio 2017

configuration: Release

platform:
- x64

branches:
  only:
  - master

shallow_clone: true

cache:
  - C:\Tools\vcpkg\installed\

# vcpkg enet, imgui are already available, but no on appveyor yet
# assimp, qt5 don't build
#  lua glm glslang gtest curl libuv zlib
install:
  - cmd: set VCPKG_DEFAULT_TRIPLET=x64-windows
  - cmd: vcpkg integrate install
  - cmd: vcpkg install curl[winssl] libpq opencl sdl2 lua libuv qt5-base
  # Install OpenCL Runtime
  - cmd: choco install opencl-intel-cpu-runtime
  #- cmd: appveyor DownloadFile "http://registrationcenter-download.intel.com/akdlm/irc_nas/12512/opencl_runtime_16.1.2_x64_setup.msi"
  #- cmd: start /wait msiexec /i opencl_runtime_16.1.2_x64_setup.msi /qn  /l*v opencl_runtime.log
  # Check if it's working
  - cmd: appveyor DownloadFile "https://ci.appveyor.com/api/projects/oblomov/clinfo/artifacts/clinfo.exe?job=platform:+x64" -FileName clinfo.exe
  - clinfo.exe

build_script:
  - md build
  - cd build
  - cmake .. -DDISABLE_UNITY=On
  - cmake --build .
  - dir

artifacts:
  - name: Tests
    path: build/vengi-tests-core.exe

services:
  - postgresql          # start PostgreSQL 9.5 service

test_script:
  - cmd: build/vengi-tests-core.exe --gtest_output=xml:tests.xml

on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
