site_name: vengi - voxel engine and its tools

docs_dir: docs
site_dir: build/docs

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages: [cpp]

markdown_extensions:
  - toc:
      toc_depth: 2

nav:
  - README.md
  - Basics:
      - Dependencies.md
      - Compilation.md
      - Configuration.md
      - Formats.md
      - CHANGELOG.md
  - VoxEdit:
      - voxedit/Index.md
      - voxedit/LUAScript.md
  - Client/Server:
      - server/Index.md
      - server/Setup.md
  - Tools:
      - VoxConvert: voxconvert/Index.md
      - Thumbnailer: thumbnailer/Index.md
      - MapView: mapview/Index.md
  - Development:
      - Visual Tests: VisualTests.md
      - Game Design: GameDesign.md
      - Shader integration: ShaderTool.md
      - Compute Shader integration: ComputeShaderTool.md
      - Persistence: Persistence.md
      - AI development: AIRemoteDebugger.md
