name: build

on: [push, pull_request]

jobs:
    mac:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v1
        - name: macOS
          run: |
            brew install qt5 mosquitto curl-openssl zlib libuv sdl2 assimp libpq sdl2_mixer
            mkdir build
            cd build
            cmake ..
            make
    linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Linux
          run: |
            sudo apt-get update
            sudo apt-get install libglm-dev libassimp-dev lua5.3 liblua5.3-dev libsdl2-dev postgresql-server-dev-10 libpq-dev libenet-dev libgtk-3-dev qt5-default qttools5-dev qttools5-dev-tools opencl-c-headers wayland-protocols pkg-config uuid-dev
            mkdir build
            cd build
            cmake ..
            make
    windows:
        runs-on: wińdows-latest
        steps:
        - uses: actions/checkout@v1
        - name: Windows
          run: |
            vcpkg install sdl2 curl libuv zlib libpq lua glm glslang gtest qt5
            mkdir build
            cd build
            cmake ..
            make
